/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as appAppRouteRouteImport } from './routes/(app)/_app/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicPricingRouteImport } from './routes/(public)/pricing'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as McpToolsDotjsonRouteImport } from './routes/mcp_.tools[.]json'
import { Route as publicConnectDoneRouteImport } from './routes/(public)/connect/done'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiConnectProviderRouteImport } from './routes/api/connect/$provider'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as appAppApiKeysIndexRouteImport } from './routes/(app)/_app/api-keys/index'
import { Route as appAppChannelsIndexRouteImport } from './routes/(app)/_app/channels/index'
import { Route as appAppLibraryIndexRouteImport } from './routes/(app)/_app/library/index'
import { Route as appAppPublishIndexRouteImport } from './routes/(app)/_app/publish/index'
import { Route as appAppQueueIndexRouteImport } from './routes/(app)/_app/queue/index'
import { Route as appAppSettingsAccountRouteImport } from './routes/(app)/_app/settings/account'
import { Route as appAppSettingsProfileRouteImport } from './routes/(app)/_app/settings/profile'
import { Route as ApiConnectProviderCallbackRouteImport } from './routes/api/connect/$provider.callback'
import { Route as ApiStorageFileSplatRouteImport } from './routes/api/storage/file/$'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRouteRoute = appAppRouteRouteImport.update({
  id: '/(app)/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPricingRoute = publicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const McpToolsDotjsonRoute = McpToolsDotjsonRouteImport.update({
  id: '/mcp_/tools.json',
  path: '/mcp/tools.json',
  getParentRoute: () => rootRouteImport,
} as any)
const publicConnectDoneRoute = publicConnectDoneRouteImport.update({
  id: '/connect/done',
  path: '/connect/done',
  getParentRoute: () => publicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectProviderRoute = ApiConnectProviderRouteImport.update({
  id: '/api/connect/$provider',
  path: '/api/connect/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppApiKeysIndexRoute = appAppApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppChannelsIndexRoute = appAppChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppLibraryIndexRoute = appAppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppPublishIndexRoute = appAppPublishIndexRouteImport.update({
  id: '/publish/',
  path: '/publish/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppQueueIndexRoute = appAppQueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppSettingsAccountRoute = appAppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => appAppRouteRoute,
} as any)
const appAppSettingsProfileRoute = appAppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => appAppRouteRoute,
} as any)
const ApiConnectProviderCallbackRoute =
  ApiConnectProviderCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiConnectProviderRoute,
  } as any)
const ApiStorageFileSplatRoute = ApiStorageFileSplatRouteImport.update({
  id: '/api/storage/file/$',
  path: '/api/storage/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pricing': typeof publicPricingRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/mcp/tools.json': typeof McpToolsDotjsonRoute
  '/': typeof publicIndexRoute
  '/connect/done': typeof publicConnectDoneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/$provider': typeof ApiConnectProviderRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/settings/account': typeof appAppSettingsAccountRoute
  '/settings/profile': typeof appAppSettingsProfileRoute
  '/api/connect/$provider/callback': typeof ApiConnectProviderCallbackRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/api-keys/': typeof appAppApiKeysIndexRoute
  '/channels/': typeof appAppChannelsIndexRoute
  '/library/': typeof appAppLibraryIndexRoute
  '/publish/': typeof appAppPublishIndexRoute
  '/queue/': typeof appAppQueueIndexRoute
}
export interface FileRoutesByTo {
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/pricing': typeof publicPricingRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/mcp/tools.json': typeof McpToolsDotjsonRoute
  '/': typeof publicIndexRoute
  '/connect/done': typeof publicConnectDoneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/$provider': typeof ApiConnectProviderRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/settings/account': typeof appAppSettingsAccountRoute
  '/settings/profile': typeof appAppSettingsProfileRoute
  '/api/connect/$provider/callback': typeof ApiConnectProviderCallbackRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/api-keys': typeof appAppApiKeysIndexRoute
  '/channels': typeof appAppChannelsIndexRoute
  '/library': typeof appAppLibraryIndexRoute
  '/publish': typeof appAppPublishIndexRoute
  '/queue': typeof appAppQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(app)/_app': typeof appAppRouteRouteWithChildren
  '/(public)/pricing': typeof publicPricingRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/mcp_/tools.json': typeof McpToolsDotjsonRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/connect/done': typeof publicConnectDoneRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/$provider': typeof ApiConnectProviderRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/(app)/_app/settings/account': typeof appAppSettingsAccountRoute
  '/(app)/_app/settings/profile': typeof appAppSettingsProfileRoute
  '/api/connect/$provider/callback': typeof ApiConnectProviderCallbackRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/(app)/_app/api-keys/': typeof appAppApiKeysIndexRoute
  '/(app)/_app/channels/': typeof appAppChannelsIndexRoute
  '/(app)/_app/library/': typeof appAppLibraryIndexRoute
  '/(app)/_app/publish/': typeof appAppPublishIndexRoute
  '/(app)/_app/queue/': typeof appAppQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms.txt'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/mcp/tools.json'
    | '/'
    | '/connect/done'
    | '/api/auth/$'
    | '/api/connect/$provider'
    | '/api/v1/$'
    | '/api/v1/openapi.json'
    | '/settings/account'
    | '/settings/profile'
    | '/api/connect/$provider/callback'
    | '/api/storage/file/$'
    | '/api-keys/'
    | '/channels/'
    | '/library/'
    | '/publish/'
    | '/queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms.txt'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/mcp/tools.json'
    | '/'
    | '/connect/done'
    | '/api/auth/$'
    | '/api/connect/$provider'
    | '/api/v1/$'
    | '/api/v1/openapi.json'
    | '/settings/account'
    | '/settings/profile'
    | '/api/connect/$provider/callback'
    | '/api/storage/file/$'
    | '/api-keys'
    | '/channels'
    | '/library'
    | '/publish'
    | '/queue'
  id:
    | '__root__'
    | '/(public)'
    | '/llms.txt'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(app)/_app'
    | '/(public)/pricing'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/mcp_/tools.json'
    | '/(public)/'
    | '/(public)/connect/done'
    | '/api/auth/$'
    | '/api/connect/$provider'
    | '/api/v1/$'
    | '/api/v1/openapi.json'
    | '/(app)/_app/settings/account'
    | '/(app)/_app/settings/profile'
    | '/api/connect/$provider/callback'
    | '/api/storage/file/$'
    | '/(app)/_app/api-keys/'
    | '/(app)/_app/channels/'
    | '/(app)/_app/library/'
    | '/(app)/_app/publish/'
    | '/(app)/_app/queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  appAppRouteRoute: typeof appAppRouteRouteWithChildren
  McpToolsDotjsonRoute: typeof McpToolsDotjsonRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConnectProviderRoute: typeof ApiConnectProviderRouteWithChildren
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiStorageFileSplatRoute: typeof ApiStorageFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/pricing': {
      id: '/(public)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof publicPricingRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/mcp_/tools.json': {
      id: '/mcp_/tools.json'
      path: '/mcp/tools.json'
      fullPath: '/mcp/tools.json'
      preLoaderRoute: typeof McpToolsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/connect/done': {
      id: '/(public)/connect/done'
      path: '/connect/done'
      fullPath: '/connect/done'
      preLoaderRoute: typeof publicConnectDoneRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect/$provider': {
      id: '/api/connect/$provider'
      path: '/api/connect/$provider'
      fullPath: '/api/connect/$provider'
      preLoaderRoute: typeof ApiConnectProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/api-keys/': {
      id: '/(app)/_app/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof appAppApiKeysIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/channels/': {
      id: '/(app)/_app/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof appAppChannelsIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/library/': {
      id: '/(app)/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof appAppLibraryIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/publish/': {
      id: '/(app)/_app/publish/'
      path: '/publish'
      fullPath: '/publish/'
      preLoaderRoute: typeof appAppPublishIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/queue/': {
      id: '/(app)/_app/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof appAppQueueIndexRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/settings/account': {
      id: '/(app)/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof appAppSettingsAccountRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/(app)/_app/settings/profile': {
      id: '/(app)/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof appAppSettingsProfileRouteImport
      parentRoute: typeof appAppRouteRoute
    }
    '/api/connect/$provider/callback': {
      id: '/api/connect/$provider/callback'
      path: '/callback'
      fullPath: '/api/connect/$provider/callback'
      preLoaderRoute: typeof ApiConnectProviderCallbackRouteImport
      parentRoute: typeof ApiConnectProviderRoute
    }
    '/api/storage/file/$': {
      id: '/api/storage/file/$'
      path: '/api/storage/file/$'
      fullPath: '/api/storage/file/$'
      preLoaderRoute: typeof ApiStorageFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicRouteRouteChildren {
  publicPricingRoute: typeof publicPricingRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
  publicConnectDoneRoute: typeof publicConnectDoneRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPricingRoute: publicPricingRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
  publicConnectDoneRoute: publicConnectDoneRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface appAppRouteRouteChildren {
  appAppSettingsAccountRoute: typeof appAppSettingsAccountRoute
  appAppSettingsProfileRoute: typeof appAppSettingsProfileRoute
  appAppApiKeysIndexRoute: typeof appAppApiKeysIndexRoute
  appAppChannelsIndexRoute: typeof appAppChannelsIndexRoute
  appAppLibraryIndexRoute: typeof appAppLibraryIndexRoute
  appAppPublishIndexRoute: typeof appAppPublishIndexRoute
  appAppQueueIndexRoute: typeof appAppQueueIndexRoute
}

const appAppRouteRouteChildren: appAppRouteRouteChildren = {
  appAppSettingsAccountRoute: appAppSettingsAccountRoute,
  appAppSettingsProfileRoute: appAppSettingsProfileRoute,
  appAppApiKeysIndexRoute: appAppApiKeysIndexRoute,
  appAppChannelsIndexRoute: appAppChannelsIndexRoute,
  appAppLibraryIndexRoute: appAppLibraryIndexRoute,
  appAppPublishIndexRoute: appAppPublishIndexRoute,
  appAppQueueIndexRoute: appAppQueueIndexRoute,
}

const appAppRouteRouteWithChildren = appAppRouteRoute._addFileChildren(
  appAppRouteRouteChildren,
)

interface ApiConnectProviderRouteChildren {
  ApiConnectProviderCallbackRoute: typeof ApiConnectProviderCallbackRoute
}

const ApiConnectProviderRouteChildren: ApiConnectProviderRouteChildren = {
  ApiConnectProviderCallbackRoute: ApiConnectProviderCallbackRoute,
}

const ApiConnectProviderRouteWithChildren =
  ApiConnectProviderRoute._addFileChildren(ApiConnectProviderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  appAppRouteRoute: appAppRouteRouteWithChildren,
  McpToolsDotjsonRoute: McpToolsDotjsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConnectProviderRoute: ApiConnectProviderRouteWithChildren,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiStorageFileSplatRoute: ApiStorageFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
