/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as RssXmlRouteImport } from './routes/rss.xml'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as publicBlogIndexRouteImport } from './routes/(public)/blog/index'
import { Route as publicBlogSlugRouteImport } from './routes/(public)/blog/$slug'
import { Route as publicBlogNewRouteImport } from './routes/(public)/blog/new'
import { Route as ApiAiCompleteRouteImport } from './routes/api/ai/complete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPostsMcpRouteImport } from './routes/api/posts/mcp'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as appAppDashboardIndexRouteImport } from './routes/(app)/_app/dashboard/index'
import { Route as appAppSettingsAccountRouteImport } from './routes/(app)/_app/settings/account'
import { Route as appAppSettingsProfileRouteImport } from './routes/(app)/_app/settings/profile'
import { Route as publicBlogSlugEditRouteImport } from './routes/(public)/blog/$slug_.edit'
import { Route as ApiStorageFileSplatRouteImport } from './routes/api/storage/file/$'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssXmlRoute = RssXmlRouteImport.update({
  id: '/rss/xml',
  path: '/rss/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogIndexRoute = publicBlogIndexRouteImport.update({
  id: '/(public)/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogSlugRoute = publicBlogSlugRouteImport.update({
  id: '/(public)/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogNewRoute = publicBlogNewRouteImport.update({
  id: '/(public)/blog/new',
  path: '/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCompleteRoute = ApiAiCompleteRouteImport.update({
  id: '/api/ai/complete',
  path: '/api/ai/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsMcpRoute = ApiPostsMcpRouteImport.update({
  id: '/api/posts/mcp',
  path: '/api/posts/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppDashboardIndexRoute = appAppDashboardIndexRouteImport.update({
  id: '/(app)/_app/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppSettingsAccountRoute = appAppSettingsAccountRouteImport.update({
  id: '/(app)/_app/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppSettingsProfileRoute = appAppSettingsProfileRouteImport.update({
  id: '/(app)/_app/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogSlugEditRoute = publicBlogSlugEditRouteImport.update({
  id: '/(public)/blog/$slug_/edit',
  path: '/blog/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileSplatRoute = ApiStorageFileSplatRouteImport.update({
  id: '/api/storage/file/$',
  path: '/api/storage/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof publicAboutRoute
  '/api/og': typeof ApiOgRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof publicIndexRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/blog/new': typeof publicBlogNewRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/mcp': typeof ApiPostsMcpRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/blog/': typeof publicBlogIndexRoute
  '/settings/account': typeof appAppSettingsAccountRoute
  '/settings/profile': typeof appAppSettingsProfileRoute
  '/blog/$slug/edit': typeof publicBlogSlugEditRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/dashboard/': typeof appAppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof publicAboutRoute
  '/api/og': typeof ApiOgRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof publicIndexRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/blog/new': typeof publicBlogNewRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/mcp': typeof ApiPostsMcpRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/blog': typeof publicBlogIndexRoute
  '/settings/account': typeof appAppSettingsAccountRoute
  '/settings/profile': typeof appAppSettingsProfileRoute
  '/blog/$slug/edit': typeof publicBlogSlugEditRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/dashboard': typeof appAppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/about': typeof publicAboutRoute
  '/api/og': typeof ApiOgRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/rss/xml': typeof RssXmlRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/blog/$slug': typeof publicBlogSlugRoute
  '/(public)/blog/new': typeof publicBlogNewRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posts/mcp': typeof ApiPostsMcpRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/(public)/blog/': typeof publicBlogIndexRoute
  '/(app)/_app/settings/account': typeof appAppSettingsAccountRoute
  '/(app)/_app/settings/profile': typeof appAppSettingsProfileRoute
  '/(public)/blog/$slug_/edit': typeof publicBlogSlugEditRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/(app)/_app/dashboard/': typeof appAppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/api/og'
    | '/robots/txt'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/'
    | '/blog/$slug'
    | '/blog/new'
    | '/api/ai/complete'
    | '/api/auth/$'
    | '/api/posts/mcp'
    | '/api/storage/upload'
    | '/blog/'
    | '/settings/account'
    | '/settings/profile'
    | '/blog/$slug/edit'
    | '/api/storage/file/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/api/og'
    | '/robots/txt'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/'
    | '/blog/$slug'
    | '/blog/new'
    | '/api/ai/complete'
    | '/api/auth/$'
    | '/api/posts/mcp'
    | '/api/storage/upload'
    | '/blog'
    | '/settings/account'
    | '/settings/profile'
    | '/blog/$slug/edit'
    | '/api/storage/file/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/(public)/about'
    | '/api/og'
    | '/robots/txt'
    | '/rss/xml'
    | '/sitemap/xml'
    | '/(public)/'
    | '/(public)/blog/$slug'
    | '/(public)/blog/new'
    | '/api/ai/complete'
    | '/api/auth/$'
    | '/api/posts/mcp'
    | '/api/storage/upload'
    | '/(public)/blog/'
    | '/(app)/_app/settings/account'
    | '/(app)/_app/settings/profile'
    | '/(public)/blog/$slug_/edit'
    | '/api/storage/file/$'
    | '/(app)/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  ApiOgRoute: typeof ApiOgRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  RssXmlRoute: typeof RssXmlRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  publicIndexRoute: typeof publicIndexRoute
  publicBlogSlugRoute: typeof publicBlogSlugRoute
  publicBlogNewRoute: typeof publicBlogNewRoute
  ApiAiCompleteRoute: typeof ApiAiCompleteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPostsMcpRoute: typeof ApiPostsMcpRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  publicBlogIndexRoute: typeof publicBlogIndexRoute
  appAppSettingsAccountRoute: typeof appAppSettingsAccountRoute
  appAppSettingsProfileRoute: typeof appAppSettingsProfileRoute
  publicBlogSlugEditRoute: typeof publicBlogSlugEditRoute
  ApiStorageFileSplatRoute: typeof ApiStorageFileSplatRoute
  appAppDashboardIndexRoute: typeof appAppDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss/xml': {
      id: '/rss/xml'
      path: '/rss/xml'
      fullPath: '/rss/xml'
      preLoaderRoute: typeof RssXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/': {
      id: '/(public)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof publicBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/$slug': {
      id: '/(public)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof publicBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/new': {
      id: '/(public)/blog/new'
      path: '/blog/new'
      fullPath: '/blog/new'
      preLoaderRoute: typeof publicBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/complete': {
      id: '/api/ai/complete'
      path: '/api/ai/complete'
      fullPath: '/api/ai/complete'
      preLoaderRoute: typeof ApiAiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/mcp': {
      id: '/api/posts/mcp'
      path: '/api/posts/mcp'
      fullPath: '/api/posts/mcp'
      preLoaderRoute: typeof ApiPostsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/dashboard/': {
      id: '/(app)/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appAppDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/settings/account': {
      id: '/(app)/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof appAppSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/settings/profile': {
      id: '/(app)/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof appAppSettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/$slug_/edit': {
      id: '/(public)/blog/$slug_/edit'
      path: '/blog/$slug/edit'
      fullPath: '/blog/$slug/edit'
      preLoaderRoute: typeof publicBlogSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file/$': {
      id: '/api/storage/file/$'
      path: '/api/storage/file/$'
      fullPath: '/api/storage/file/$'
      preLoaderRoute: typeof ApiStorageFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  ApiOgRoute: ApiOgRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  RssXmlRoute: RssXmlRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  publicIndexRoute: publicIndexRoute,
  publicBlogSlugRoute: publicBlogSlugRoute,
  publicBlogNewRoute: publicBlogNewRoute,
  ApiAiCompleteRoute: ApiAiCompleteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPostsMcpRoute: ApiPostsMcpRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  publicBlogIndexRoute: publicBlogIndexRoute,
  appAppSettingsAccountRoute: appAppSettingsAccountRoute,
  appAppSettingsProfileRoute: appAppSettingsProfileRoute,
  publicBlogSlugEditRoute: publicBlogSlugEditRoute,
  ApiStorageFileSplatRoute: ApiStorageFileSplatRoute,
  appAppDashboardIndexRoute: appAppDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
