/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiConnectProviderRouteImport } from './routes/api/connect/$provider'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiV1AccountsRouteImport } from './routes/api/v1/accounts'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as appAppApiKeysIndexRouteImport } from './routes/(app)/_app/api-keys/index'
import { Route as appAppChannelsIndexRouteImport } from './routes/(app)/_app/channels/index'
import { Route as appAppPublishIndexRouteImport } from './routes/(app)/_app/publish/index'
import { Route as appAppSettingsAccountRouteImport } from './routes/(app)/_app/settings/account'
import { Route as appAppSettingsProfileRouteImport } from './routes/(app)/_app/settings/profile'
import { Route as ApiConnectProviderCallbackRouteImport } from './routes/api/connect/$provider.callback'
import { Route as ApiStorageFileSplatRouteImport } from './routes/api/storage/file/$'
import { Route as ApiV1PostsIdRouteImport } from './routes/api/v1/posts.$id'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectProviderRoute = ApiConnectProviderRouteImport.update({
  id: '/api/connect/$provider',
  path: '/api/connect/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsRoute = ApiV1AccountsRouteImport.update({
  id: '/api/v1/accounts',
  path: '/api/v1/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppApiKeysIndexRoute = appAppApiKeysIndexRouteImport.update({
  id: '/(app)/_app/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppChannelsIndexRoute = appAppChannelsIndexRouteImport.update({
  id: '/(app)/_app/channels/',
  path: '/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppPublishIndexRoute = appAppPublishIndexRouteImport.update({
  id: '/(app)/_app/publish/',
  path: '/publish/',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppSettingsAccountRoute = appAppSettingsAccountRouteImport.update({
  id: '/(app)/_app/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppSettingsProfileRoute = appAppSettingsProfileRouteImport.update({
  id: '/(app)/_app/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectProviderCallbackRoute =
  ApiConnectProviderCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiConnectProviderRoute,
  } as any)
const ApiStorageFileSplatRoute = ApiStorageFileSplatRouteImport.update({
  id: '/api/storage/file/$',
  path: '/api/storage/file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsIdRoute = ApiV1PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/mcp': typeof McpRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/$provider': typeof ApiConnectProviderRouteWithChildren
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/settings/account': typeof appAppSettingsAccountRoute
  '/settings/profile': typeof appAppSettingsProfileRoute
  '/api/connect/$provider/callback': typeof ApiConnectProviderCallbackRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRoute
  '/api-keys/': typeof appAppApiKeysIndexRoute
  '/channels/': typeof appAppChannelsIndexRoute
  '/publish/': typeof appAppPublishIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/$provider': typeof ApiConnectProviderRouteWithChildren
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/settings/account': typeof appAppSettingsAccountRoute
  '/settings/profile': typeof appAppSettingsProfileRoute
  '/api/connect/$provider/callback': typeof ApiConnectProviderCallbackRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRoute
  '/api-keys': typeof appAppApiKeysIndexRoute
  '/channels': typeof appAppChannelsIndexRoute
  '/publish': typeof appAppPublishIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/mcp': typeof McpRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/(public)/': typeof publicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/connect/$provider': typeof ApiConnectProviderRouteWithChildren
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/(app)/_app/settings/account': typeof appAppSettingsAccountRoute
  '/(app)/_app/settings/profile': typeof appAppSettingsProfileRoute
  '/api/connect/$provider/callback': typeof ApiConnectProviderCallbackRoute
  '/api/storage/file/$': typeof ApiStorageFileSplatRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRoute
  '/(app)/_app/api-keys/': typeof appAppApiKeysIndexRoute
  '/(app)/_app/channels/': typeof appAppChannelsIndexRoute
  '/(app)/_app/publish/': typeof appAppPublishIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/mcp'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/'
    | '/api/auth/$'
    | '/api/connect/$provider'
    | '/api/media/upload'
    | '/api/storage/upload'
    | '/api/v1/accounts'
    | '/api/v1/posts'
    | '/settings/account'
    | '/settings/profile'
    | '/api/connect/$provider/callback'
    | '/api/storage/file/$'
    | '/api/v1/posts/$id'
    | '/api-keys/'
    | '/channels/'
    | '/publish/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/'
    | '/api/auth/$'
    | '/api/connect/$provider'
    | '/api/media/upload'
    | '/api/storage/upload'
    | '/api/v1/accounts'
    | '/api/v1/posts'
    | '/settings/account'
    | '/settings/profile'
    | '/api/connect/$provider/callback'
    | '/api/storage/file/$'
    | '/api/v1/posts/$id'
    | '/api-keys'
    | '/channels'
    | '/publish'
  id:
    | '__root__'
    | '/mcp'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/(public)/'
    | '/api/auth/$'
    | '/api/connect/$provider'
    | '/api/media/upload'
    | '/api/storage/upload'
    | '/api/v1/accounts'
    | '/api/v1/posts'
    | '/(app)/_app/settings/account'
    | '/(app)/_app/settings/profile'
    | '/api/connect/$provider/callback'
    | '/api/storage/file/$'
    | '/api/v1/posts/$id'
    | '/(app)/_app/api-keys/'
    | '/(app)/_app/channels/'
    | '/(app)/_app/publish/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  McpRoute: typeof McpRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConnectProviderRoute: typeof ApiConnectProviderRouteWithChildren
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiV1AccountsRoute: typeof ApiV1AccountsRoute
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
  appAppSettingsAccountRoute: typeof appAppSettingsAccountRoute
  appAppSettingsProfileRoute: typeof appAppSettingsProfileRoute
  ApiStorageFileSplatRoute: typeof ApiStorageFileSplatRoute
  appAppApiKeysIndexRoute: typeof appAppApiKeysIndexRoute
  appAppChannelsIndexRoute: typeof appAppChannelsIndexRoute
  appAppPublishIndexRoute: typeof appAppPublishIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect/$provider': {
      id: '/api/connect/$provider'
      path: '/api/connect/$provider'
      fullPath: '/api/connect/$provider'
      preLoaderRoute: typeof ApiConnectProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts': {
      id: '/api/v1/accounts'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts'
      preLoaderRoute: typeof ApiV1AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/api-keys/': {
      id: '/(app)/_app/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof appAppApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/channels/': {
      id: '/(app)/_app/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof appAppChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/publish/': {
      id: '/(app)/_app/publish/'
      path: '/publish'
      fullPath: '/publish/'
      preLoaderRoute: typeof appAppPublishIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/settings/account': {
      id: '/(app)/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof appAppSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/settings/profile': {
      id: '/(app)/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof appAppSettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connect/$provider/callback': {
      id: '/api/connect/$provider/callback'
      path: '/callback'
      fullPath: '/api/connect/$provider/callback'
      preLoaderRoute: typeof ApiConnectProviderCallbackRouteImport
      parentRoute: typeof ApiConnectProviderRoute
    }
    '/api/storage/file/$': {
      id: '/api/storage/file/$'
      path: '/api/storage/file/$'
      fullPath: '/api/storage/file/$'
      preLoaderRoute: typeof ApiStorageFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/$id': {
      id: '/api/v1/posts/$id'
      path: '/$id'
      fullPath: '/api/v1/posts/$id'
      preLoaderRoute: typeof ApiV1PostsIdRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
  }
}

interface ApiConnectProviderRouteChildren {
  ApiConnectProviderCallbackRoute: typeof ApiConnectProviderCallbackRoute
}

const ApiConnectProviderRouteChildren: ApiConnectProviderRouteChildren = {
  ApiConnectProviderCallbackRoute: ApiConnectProviderCallbackRoute,
}

const ApiConnectProviderRouteWithChildren =
  ApiConnectProviderRoute._addFileChildren(ApiConnectProviderRouteChildren)

interface ApiV1PostsRouteChildren {
  ApiV1PostsIdRoute: typeof ApiV1PostsIdRoute
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsIdRoute: ApiV1PostsIdRoute,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  McpRoute: McpRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConnectProviderRoute: ApiConnectProviderRouteWithChildren,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiV1AccountsRoute: ApiV1AccountsRoute,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
  appAppSettingsAccountRoute: appAppSettingsAccountRoute,
  appAppSettingsProfileRoute: appAppSettingsProfileRoute,
  ApiStorageFileSplatRoute: ApiStorageFileSplatRoute,
  appAppApiKeysIndexRoute: appAppApiKeysIndexRoute,
  appAppChannelsIndexRoute: appAppChannelsIndexRoute,
  appAppPublishIndexRoute: appAppPublishIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
